language: cpp
compiler: gcc

before_install:
    - sudo apt-add-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq
    - sudo apt-get install -qq gcc-4.8 g++-4.8
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 100
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 100
    - sudo update-alternatives --install /usr/bin/cpp cpp /usr/bin/cpp-4.8 100
    - sudo apt-get install -qq libgtkmm-3.0-dev
    - sudo apt-get install -qq libgtest-dev
    - pushd /usr/src/gtest
    - sudo cmake CMakeLists.txt
    - sudo make
    - sudo cp *.a /usr/lib
    - popd

script:
    - mkdir ./build
    - cd ./build
    - cmake ..
    - make
    - make test
